Working on creating an action prefab with GUI as called by the constructor from the abstract type
Breaking at
	GameObject newAction = Instantiate(actionPrefab, actionPosition, Quaternion.identity, GameObject.FindGameObjectWithTag("ActionTrackCanvas").transform);
Probably failing at
	 GameObject actionPrefab = Resources.Load("Assets/Prefabs/Action") as GameObject;

Since I dont have an inspector on this full script (no associated controller) either maybe pass in the prefab from some other location or figure out how to get a reference to it as a game object (using Resources.Load here)

If you wanna take a crack at it while I am gone go for it!

NullReferenceException: Object reference not set to an instance of an object
Action..ctor (System.Int32 actionIdx, System.Int32 trackIdx) (at Assets/Scripts/Action.cs:19)
RocketFireAction..ctor (System.Int32 actionIdx, System.Int32 trackIdx) (at Assets/Scripts/Action.cs:49)
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Activator.CreateInstance (System.Type type, System.Object[] args) (at <fb001e01371b4adca20013e0ac763896>:0)
Track.addAction (System.Int32 actionIdx, System.Int32 trackIdx) (at Assets/Scripts/Track.cs:47)
Track..ctor (System.Int32 size, System.Int32 tIdx, System.Type[] possibleActions) (at Assets/Scripts/Track.cs:18)
TrackController.Start () (at Assets/Scripts/TrackController.cs:29)